export const FETCH_EXERCICE_INIT = 'FETCH_EXERCICE_INIT';
export const FETCH_EXERCICE_SUCCESS = 'FETCH_EXERCICE_SUCCESS';
export const FETCH_EXERCICE_FAIL = 'FETCH_EXERCICE_FAIL';
export const SET_NOW_EXERCICE = 'SET_NOW_EXERCICE';
export const NEXT_EXERCICE = 'NEXT_EXERCICE';
export const PREV_EXERCICE = 'PREV_EXERCICE';
export const SHOWN_MATERIALS = 'SHOWN_MATERIALS';
export const HIDDEN_MATERIALS = 'HIDDEN_MATERIALS';
