export const DRAWING_STATION_USER = 'DRAWING_STATION_USER';
export const DRAWING_STATION_LOCAL_VERSION = 'DRAWING_STATION_LOCAL_VERSION';
export const DRAWING_STATION_LOCAL_DATA = 'DRAWING_STATION_LOCAL_DATA';
